### PR TITLE
Milestone 2: Testing the tictac toe

### PR DESCRIPTION
**Pull request by peterrobert**
In this milestone I did the following:

1. Created tests for all pure functions in my tictac toe game.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] We recommend the use of es6 arrow functions, see below
```
const GameBoard = () => {
  # Code
}
```
- [x] Install all the required dependencies and run eslint and stylelint commands, if errors, kindly solve them. [Follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
- [x] Your tests are failing, kindly solve all these errors
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by peterrobert** [comment]
To run the tests just run npm run test in your terminal

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team
### I am still experiencing errors on my end when I run the test command. See the image below:-
test
### Make the changes and submit for another cod review. Good luck.
- Happy coding!

**Comment by peterrobert** [comment]
Hello tse, kindly just double check your system or kindly check if you are in the right branch. You should be in the testing branch and then run npm run test. I tried reaching you on slack but I didn't get your name.

kindly reached me on slack at @peterrobert

**Review by rOluochKe — APPROVED** [review]
Hello @peterrobert 
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
